In [8]:
from sklearn import datasets, model_selection, naive_bayes
import numpy as np
import pandas as pnd
from matplotlib import pyplot as plt

In [3]:
ds_1 = datasets.load_digits()
ds_2 = datasets.load_breast_cancer()

In [10]:
ds_1.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [11]:
ds_1.target

array([0, 1, 2, ..., 8, 9, 8])

In [12]:
ds_2.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [14]:
ds_2.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [15]:
X_1 = ds_1.data
y_1 = ds_1.target
X_2 = ds_2.data
y_2 = ds_2.target

In [18]:
print('BernoulliNB for digits:', model_selection.cross_val_score(naive_bayes.BernoulliNB(), X_1, y_1).mean())
print('BernoulliNB for breast cancer:', model_selection.cross_val_score(naive_bayes.BernoulliNB(), X_2, y_2).mean())
print('MultinomialNB for digits:', model_selection.cross_val_score(naive_bayes.MultinomialNB(), X_1, y_1).mean())
print('MultinomialNB for breast cancer:', model_selection.cross_val_score(naive_bayes.MultinomialNB(), X_2, y_2).mean())
print('BernoulliNB for digits:', model_selection.cross_val_score(naive_bayes.GaussianNB(), X_1, y_1).mean())
print('BernoulliNB for breast cancer:', model_selection.cross_val_score(naive_bayes.GaussianNB(), X_2, y_2).mean())

BernoulliNB for digits: 0.8241736304549674
BernoulliNB for breast cancer: 0.6274181027790716
MultinomialNB for digits: 0.8703497369235531
MultinomialNB for breast cancer: 0.8963204471355379
BernoulliNB for digits: 0.8069281956050759
BernoulliNB for breast cancer: 0.9385188635305075


In [19]:
def write_answer(i, answer):
    f = open('anwer_relax' + str(i) + '.txt', 'w')
    f.write(str(answer))

In [20]:
write_answer(1, 0.9385188635305075)
write_answer(2, 0.8703497369235531)
write_answer(3, '2 3')